// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1ZJvsqWPTYIG_OkW5tcGJZmvUnigp0A',
    appId: '1:341152015809:web:f03427f31b6a1abbbbbb40',
    messagingSenderId: '341152015809',
    projectId: 'quotidiant-app',
    authDomain: 'quotidiant-app.firebaseapp.com',
    storageBucket: 'quotidiant-app.appspot.com',
    measurementId: 'G-SBXVF17M7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULkEQQc79zNLmUuqUC448darQuzYyHkA',
    appId: '1:341152015809:android:afbc24e2b7cb1d94bbbb40',
    messagingSenderId: '341152015809',
    projectId: 'quotidiant-app',
    storageBucket: 'quotidiant-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTV7zoJkLOj-QOoudxDaQB8ep_8-PQe-g',
    appId: '1:341152015809:ios:a52081f7ab64ed22bbbb40',
    messagingSenderId: '341152015809',
    projectId: 'quotidiant-app',
    storageBucket: 'quotidiant-app.appspot.com',
    iosClientId: '341152015809-vsdjgmcfiqak5t9fbh3vo7c18gkv3k3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotidiantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTV7zoJkLOj-QOoudxDaQB8ep_8-PQe-g',
    appId: '1:341152015809:ios:a52081f7ab64ed22bbbb40',
    messagingSenderId: '341152015809',
    projectId: 'quotidiant-app',
    storageBucket: 'quotidiant-app.appspot.com',
    iosClientId: '341152015809-vsdjgmcfiqak5t9fbh3vo7c18gkv3k3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotidiantApp',
  );
}
